### PR TITLE
Fix scp and sftp hardcoded build paths to use relative ssh path

### LINKED ISSUE #2: ssh location is hard coded in sftp
sftp user@host
exec: /u/jenkins/zopen/prod/openssh-9.3p1/bin/ssh: EDC5129I No such file or directory.
Connection closed

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
Resolves https://github.com/ZOSOpenTools/opensshport/issues/2

### CODE REVIEW

File: cicd-stable.groovy [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+                        branches: [[name: '*/main']],
+                        doGenerateSubmoduleConfigurations: false,
+                        extensions: [],
+                        userRemoteConfigs: [[url: "https://github.com/ZOSOpenTools/opensshport.git"]]])
+  }
+
+  stage('Build') {
+    build job: 'Port-Pipeline', parameters: [string(name: 'PORT_GITHUB_REPO', value: 'https://github.com/ZOSOpenTools/opensshport.git'), string(name: 'PORT_DESCRIPTION', value: 'OpenSSH' )]
+
+  string(name: 'BUILD_LINE', value: 'STABLE')]
```
Comment (MikeFultonDev) [inline cicd-stable.groovy]: have an extra square bracket

File: patches/pathnames.h.patch [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+ 
++#ifdef __MVS__
++#include <libgen.h>
++#include <sys/ps.h>
++#include <unistd.h>
++#include <stdlib.h>
++#include <stdio.h>
++
++
++char* getRelativeSSHPath() {
```
Comment (MikeFultonDev) [inline patches/pathnames.h.patch]: would it make sense to push this to zoslib? I know you brought this up before for getprogname - maybe we push it up with a new name (like you did) so that it doesn't conflict with getprogname ?

Comment (IgorTodorovskiIBM) [reply patches/pathnames.h.patch]: The function is now simplified and leverages __getprogramdir from zoslib

Comment (MikeFultonDev) [reply patches/pathnames.h.patch]: should getRelativeSSHPath be static since it's in a header file?

**Review by MikeFultonDev — APPROVED** [review]
one comment. other than that, LGTM

File: patches/pathnames.h.patch (hunk 2 above)
Comment (IgorTodorovskiIBM) [reply patches/pathnames.h.patch]: good catch, no wonder I was getting linker warnings :)

**Comment by IgorTodorovskiIBM** [comment]
Updated to 9.5 as well
